{{- if .Values.backend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: bizray-backend
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: bizray-backend
  type: {{ .Values.backend.service.type }}
  ports:
  - name: {{ .Values.backend.service.portName }}
    port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.portName }}
{{- end }}
