---
name: CD Backend
on: 
  push:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/cd-b.yaml
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    env:
      IMAGE_NAME: bizray-backend
      PROJECT_ID: ${{ vars.PROJECT_ID }}
      REGISTRY: ${{ vars.REGISTRY }}
      REPO_NAME: bizray
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: auth
      name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        token_format: access_token
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        access_token_lifetime: 300s

    - name: Login to Artifact Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ vars.REGISTRY }}
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest ./

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: 1.0.${{ github.run_number }}
      run: |-
        docker tag $IMAGE_NAME:latest $REGISTRY/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest $REGISTRY/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:$GIT_TAG
        docker push $REGISTRY/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:latest
        docker push $REGISTRY/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:$GIT_TAG